# Extract version number from "version" query parameter
map $args $version {
    default                         "2";
    "~(^|&)version=(?P<V>\d+)(&|$)" $V;
}

server {
    listen 80;
    listen [::]:80;

    root /var/lib/xroad/public;

    # Resolve /<instance>/conf to the versioned file /<instance>/conf-v<N>
    location ~ ^/.+/conf$ {
        try_files $uri-v$version =404;
        expires -1;
    }
}
