apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-db-pvc
  namespace: sidecar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-conf-pvc
  namespace: sidecar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-test-ca-pvc
  namespace: sidecar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
