quarkus:
  application:
    name: ds-identity-hub
  config:
    locations:
      - xroad-common.yaml
      - xroad-logging.yaml
  log:
    level: INFO
    category:
      "EDC":
        level: DEBUG

"%native":
  quarkus:
    config:
      locations:
        - xroad-common.yaml
        - xroad-logging.yaml
        - /etc/xroad/conf.d/local-tls.yaml
        - /etc/xroad/conf.d/local.yaml
        - /etc/xroad/db.properties
    log:
      console:
        enabled: false
      file:
        enabled: true
        path: /var/log/xroad/ds-identity-hub.log

web:
  http:
    port: 8181
    path: /api
    statuslist:
      port: "9998" # default 9999 conflicts with debug port
    did:
      port: "10100"
      path: /
    sts:
      port: "9292"
      path: /api/sts


edc:
  hostname: ${HOSTNAME}
  ih:
    did:
      public:
        hostname: ${EDC_IH_DID_PUBLIC_HOSTNAME:${HOSTNAME:localhost}}
  datasource:
    default:
      url: ${xroad.db.ds-identity-hub.hibernate.connection.url}
      user: ${xroad.db.ds-identity-hub.hibernate.connection.username}
      password: ${xroad.db.ds-identity-hub.hibernate.connection.password}
  sql:
    schema:
      autocreate: true
  iam:
    oauth2:
      jwks:
        url: https://example.com/jwks
      issuer: test-issuer
