xroad.admin-service.rate-limit-requests-per-second=100
xroad.admin-service.rate-limit-requests-per-minute=1000
xroad.admin-service.global-configuration-generation-rate-in-seconds=99999
xroad.admin-service.key-management-api-whitelist=0.0.0.0/0, ::/0
xroad.admin-service.cache-api-key-ttl=1
xroad.dataspace.issuer.host=localhost
