ARG REGISTRY_URL=localhost:5555
FROM ${REGISTRY_URL}/ss-baseline-runtime:latest

#TODO XRDDEV-2755 temporary users for PAM based auth
RUN usermod --append -G shadow xroad && \
    groupadd --system xroad-system-administrator && \
    groupadd --system xroad-security-officer && \
    groupadd --system xroad-registration-officer && \
    groupadd --system xroad-service-administrator && \
    groupadd --system xroad-securityserver-observer && \
    useradd -m xrd -s /usr/sbin/nologin -p '$6$JeOzaeWnLAQSUVuO$GOJ0wUKSVQnOR4I2JgZxdKr.kMO.YGS21SGaAshaYhayv8kSV9WuIFCZHTGAX8WRRTB/2ojuLnJg4kMoyzpcu1' && \
    usermod -a -G xroad-system-administrator xrd && \
    usermod -a -G xroad-security-officer xrd && \
    usermod -a -G xroad-registration-officer xrd && \
    usermod -a -G xroad-service-administrator xrd && \
    usermod -a -G xroad-securityserver-observer xrd

ARG USER_PASSWD=secret
RUN useradd xrd-sec && adduser xrd-sec xroad-security-officer && sh -c "echo 'xrd-sec:$USER_PASSWD' | chpasswd" \
    && useradd xrd-reg && adduser xrd-reg xroad-registration-officer && sh -c "echo 'xrd-reg:$USER_PASSWD' | chpasswd" \
    && useradd xrd-ser && adduser xrd-ser xroad-service-administrator && sh -c "echo 'xrd-ser:$USER_PASSWD' | chpasswd" \
    && useradd xrd-sys && adduser xrd-sys xroad-system-administrator && sh -c "echo 'xrd-sys:$USER_PASSWD' | chpasswd" \
    && useradd xrd-obs && adduser xrd-obs xroad-securityserver-observer && sh -c "echo 'xrd-obs:$USER_PASSWD' | chpasswd"
