#!/bin/bash

if [ "$JAVA_HOME" = "" ]
then
    javabin="java"
else
    javabin="$JAVA_HOME/bin/java"
fi

classes=build/classes/java/test
classname=ee.ria.xroad.proxy.testsuite.ProxyTestSuite

if [ "$1" = "-proxy" ]
then
    shift
    classes=build/libs/proxy-1.0.jar
    classname=ee.ria.xroad.proxy.ProxyMain
fi

$javabin -Xmx2g\
    -Dxroad.proxy.ocspCachePath=build/ocsp-cache\
    -Dxroad.tempFiles.path=build/attach-tmp\
    -Dxroad.proxy.jetty-serverproxy-configuration-file=src/test/serverproxy.xml\
    -Dxroad.proxy.jetty-ocsp-responder-configuration-file=src/test/ocsp-responder.xml\
    -Dxroad.proxy.jetty-clientproxy-configuration-file=src/test/clientproxy.xml\
    -Dxroad.proxy.client-connector-so-linger=-1\
    -Dxroad.proxy.client-httpclient-so-linger=-1\
    -Dxroad.proxy.server-connector-so-linger=-1\
    -Dlogback.configurationFile=src/test/logback-proxytest.xml\
    -cp ../common/common-test/build/libs/common-test-1.0.jar:build/libs/proxy-1.0.jar:../common/common-verifier/build/classes/test:$classes $classname $*
