/**
 * The MIT License
 *
 * Copyright (c) 2019- Nordic Institute for Interoperability Solutions (NIIS)
 * Copyright (c) 2018 Estonian Information System Authority (RIA),
 * Nordic Institute for Interoperability Solutions (NIIS), Population Register Centre (VRK)
 * Copyright (c) 2015-2017 Estonian Information System Authority (RIA), Population Register Centre (VRK)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.niis.xroad.centralserver.database.entity;
// Generated Feb 16, 2021 11:14:33 AM by Hibernate Tools 5.4.20.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TrustedAnchors generated by hbm2java
 */
@Entity
@Table(name = TrustedAnchor.TABLE_NAME)
public class TrustedAnchor extends AuditableEntity {
    public static final String TABLE_NAME = "trusted_anchors";

    private int id;
    private String instanceIdentifier;
    private byte[] trustedAnchorFile;
    private String trustedAnchorHash;
    private Date generatedAt;
    private Set<AnchorUrl> anchorUrls = new HashSet<>(0);

    public TrustedAnchor() {
        //JPA
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = TABLE_NAME + "_seq")
    @SequenceGenerator(name = TABLE_NAME + "_seq", sequenceName = TABLE_NAME + "_id_seq", allocationSize = 1)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "instance_identifier")
    public String getInstanceIdentifier() {
        return this.instanceIdentifier;
    }

    public void setInstanceIdentifier(String instanceIdentifier) {
        this.instanceIdentifier = instanceIdentifier;
    }

    @Column(name = "trusted_anchor_file")
    public byte[] getTrustedAnchorFile() {
        return this.trustedAnchorFile;
    }

    public void setTrustedAnchorFile(byte[] trustedAnchorFile) {
        this.trustedAnchorFile = trustedAnchorFile;
    }

    @Column(name = "trusted_anchor_hash")
    public String getTrustedAnchorHash() {
        return this.trustedAnchorHash;
    }

    public void setTrustedAnchorHash(String trustedAnchorHash) {
        this.trustedAnchorHash = trustedAnchorHash;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "generated_at")
    public Date getGeneratedAt() {
        return this.generatedAt;
    }

    public void setGeneratedAt(Date generatedAt) {
        this.generatedAt = generatedAt;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "trustedAnchor", cascade = CascadeType.ALL, orphanRemoval = true)
    public Set<AnchorUrl> getAnchorUrls() {
        return this.anchorUrls;
    }

    public void setAnchorUrls(Set<AnchorUrl> anchorUrls) {
        this.anchorUrls = anchorUrls;
    }

}


