xroad.common-rpc.use-tls=false
xroad.admin-service.rate-limit-enabled=false
xroad.admin-service.global-configuration-generation-rate-in-seconds=10
xroad.common-global-conf.refresh-rate=10s
xroad.signer.enforce-token-pin-policy=true
