services:
  proxy:
    volumes:
        - ./msglog_encryption_config:/opt/app/config
  openbao:
    volumes:
      - ./gpg_keys:/gpg-keys
  message-log-cli:
    volumes:
      - ./gpg_keys:/gpg-keys
      - ./msglog_encryption_config:/opt/app/config
