services:
  proxy:
    environment:
      - XROAD_PROXY_MESSAGE_LOG_TIMESTAMPER_TIMESTAMP_IMMEDIATELY=true
      - XROAD_PROXY_DSP_DATA_FLOW_ENDPOINT=http://${ENV_PREFIX:-}proxy:5590/full/api/v1/dataflows
      - XROAD_PROXY_DSP_SERVERPROXY_ENDPOINT=https://${DSP_PARTICIPANT_ID:-xrd-ss}:5500
      - XROAD_COMMON_GLOBAL_CONF_REFRESH_RATE=10S
  configuration-client:
    environment:
      - XROAD_CONFIGURATION_CLIENT_UPDATE_INTERVAL=10
  ui:
    environment:
      - XROAD_PROXY_UI_API_DATASPACE_ENABLED=true
      - XROAD_PROXY_UI_API_DATASPACE_IDENTITY_HUB_URL=https://${ENV_PREFIX:-}ds-identity-hub:7182
      - XROAD_PROXY_UI_API_DATASPACE_CONTROL_PLANE_URL=https://${ENV_PREFIX:-}ds-control-plane:8182
      - XROAD_PROXY_UI_API_DATASPACE_PARTICIPANT_ID=${DSP_PARTICIPANT_ID:-xrd-ss}
      - XROAD_PROXY_UI_API_DATASPACE_MANAGEMENT_CONTEXT_ENABLED=${DSP_MGMT_CONTEXT:-false}
      - XROAD_PROXY_UI_API_DATASPACE_ISSUER_DID=did:web:ds-issuer-service%3A6183:issuer
      - XROAD_PROXY_UI_API_DATASPACE_IDENTITY_TOKEN=eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ijc0ZjM0MjJiMzdmYzg2ODhlN2Y1YTc0MTYyN2Y4ODg5In0.eyJpc3MiOiJ0ZXN0LWlzc3VlciIsImV4cCI6MTk4OTg0MDk5NywiaWF0IjoxNzY4ODM3Mzk3LCJqdGkiOiI3ZDM1YTUwZGNmMmEyNTE2YTE1ZDgwYjJiNDFlZWRmYSIsInJvbGUiOiJhZG1pbiIsInNjb3BlIjoiaWRlbnRpdHktYXBpOmFkbWluIn0.Sf6lci00452QKz1g4pMgJF4jFJTBxRCHWFm2TdzFOJmWHI9aN1HYYjJiXa8NwMbJoKxdjLVemdOVHKTnsSMiHPo00sN30CJQwwJTxFcQVPaaTDvIqFzLRB7eAXcWr9Y4v-G0mhoRbe_15gjm1NE1_lrvAqc53D4KM2ujw3LrCHPREiNbZ_bMmsdYK1RRYzcl1T8gyIRnjmRiUvIj8Ffa7Pb5bqVLtAJTT2xnmjFCMIBoqcT16lhrI6hnjfcHGuMe3UI-ndqNuG281w0lk5qWL4-igmFsh6a5iIc2jUtccC95FboBKqsNnnaRB2qPkZfFFVNZDqf-4ul2ZxjrULCfKw
      - XROAD_PROXY_UI_API_DATASPACE_CONTROL_PLANE_TOKEN=eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ijc0ZjM0MjJiMzdmYzg2ODhlN2Y1YTc0MTYyN2Y4ODg5In0.eyJpc3MiOiJ0ZXN0LWlzc3VlciIsImV4cCI6MTk4OTg0MDk5NywiaWF0IjoxNzY4ODM3Mzk3LCJqdGkiOiI3ZDM1YTUwZGNmMmEyNTE2YTE1ZDgwYjJiNDFlZWRmYSIsInJvbGUiOiJwcm92aXNpb25lciIsInNjb3BlIjoibWFuYWdlbWVudC1hcGk6YWRtaW4ifQ.olwdJ4uNvZ2sgadFyqHBNPz0hCN1E-LorR9X4OCjp9-a0vslHdEW6yQOymTAzj2z48mfnQbV3Hifboz_ItWdDIemvC99yaTU923f8O0ORZaSfoCViYxwu4WtBROt9vlnZHVk9nNPQPI5sVsIlnwQ-fuPT1aoVa8fpWFVCzbdmBrM3PdJk7PmOQn2NyPXfrQwkUSnf7zcECPl1rwT6Ylt95W5zBO0DG7nqQLqpDS9qlbTvHX54waGymFHOdR1uT-8lyYhefJMmOFGHG1er_w4g2w5kklO3C4tlQiBCTkqni1dmd0mT7MXf-gWjufjTdrOUpsDtA5B8FFRkySDGVj9nw
  db-messagelog:
    ports:
      - "0:5432"
