services:
  proxy:
    environment:
      - XROAD_PROXY_MESSAGE_LOG_TIMESTAMPER_TIMESTAMP_IMMEDIATELY=true
      - XROAD_PROXY_DSP_DATA_FLOW_ENDPOINT=http://${ENV_PREFIX:-}proxy:5590/full/api/v1/dataflows
      - XROAD_PROXY_DSP_SERVERPROXY_ENDPOINT=https://${DSP_PARTICIPANT_ID:-xrd-ss}:5500
  ui:
    environment:
      - XROAD_PROXY_UI_API_DATASPACE_ENABLED=true
      - XROAD_PROXY_UI_API_DATASPACE_IDENTITY_HUB_URL=https://${ENV_PREFIX:-}ds-identity-hub:7182
      - XROAD_PROXY_UI_API_DATASPACE_CONTROL_PLANE_URL=https://${ENV_PREFIX:-}ds-control-plane:8182
      - XROAD_PROXY_UI_API_DATASPACE_PARTICIPANT_ID=${DSP_PARTICIPANT_ID:-xrd-ss}
      - XROAD_PROXY_UI_API_DATASPACE_MANAGEMENT_CONTEXT_ENABLED=${DSP_MGMT_CONTEXT:-false}
      - XROAD_PROXY_UI_API_DATASPACE_ISSUER_DID=did:web:ds-issuer-service%3A6183:issuer
      - XROAD_PROXY_UI_API_DATASPACE_IDENTITY_TOKEN=eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ijc0ZjM0MjJiMzdmYzg2ODhlN2Y1YTc0MTYyN2Y4ODg5In0.eyJpc3MiOiJ0ZXN0LWlzc3VlciIsImV4cCI6MTk4OTg0MDk5NywiaWF0IjoxNzY4ODM3Mzk3LCJqdGkiOiI3ZDM1YTUwZGNmMmEyNTE2YTE1ZDgwYjJiNDFlZWRmYSIsInJvbGUiOiJhZG1pbiIsInNjb3BlIjoiaWRlbnRpdHktYXBpOndyaXRlIGlkZW50aXR5LWFwaTpyZWFkIn0.vKPkIJ47atCdUnH60TsGSihx54xqbpvmI-QYSIRZprkmY3Fb8zPZ4PYMrTUCu6mw-ISPyzV1fu54s5bYD4q5trjZN8hrocgWyYbPPkk-sZDqcKFwFfxcVWP7wPuRZOus_AxcxrSny0IQYzlTmmvhVqPq1MJjLSximHnY3Hg7yti_b0OZE5iBMKuoww8xlr6OXY4dpJHAvwK6vJhscoQa5Mm56GsSVto38Y4HHsKlNjJlYPpILdiiytfMS5x6AhCALRoY15_0upP-MWWe7eq_2sAv7TuEZJFIdpfpWKQG4-eMHBTNim17FZx76CG9xoYhlhrJ5WGSel_8xTJD3xSVzg
      - XROAD_PROXY_UI_API_DATASPACE_CONTROL_PLANE_TOKEN=eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ijc0ZjM0MjJiMzdmYzg2ODhlN2Y1YTc0MTYyN2Y4ODg5In0.eyJpc3MiOiJ0ZXN0LWlzc3VlciIsImV4cCI6MTk4OTg0MDk5NywiaWF0IjoxNzY4ODM3Mzk3LCJqdGkiOiI3ZDM1YTUwZGNmMmEyNTE2YTE1ZDgwYjJiNDFlZWRmYSIsInJvbGUiOiJwcm92aXNpb25lciIsInNjb3BlIjoibWFuYWdlbWVudC1hcGk6d3JpdGUgbWFuYWdlbWVudC1hcGk6cmVhZCJ9.VtgeUBJXWdZSsemdWTtvSDqdCUa1eBaqMlxbBVAAPsSjyVOb8wiDmxpTqvyLKTw9WE2WznmaOUPpWh3s4nDTjHQ51-ke_H__5WHVkwK-E97AFvInue-1lPMdIC1rNGLyZKYmQQ8DtHwZDWkgl-F4zhiyTk8Z3OBzgZpDz3BcyyJT7WLvAHp6Pk0SdHmFhA5ctvXfra4-ZkfUUudXklOEe-8Jj42v2EjF0woUk9nHoNYA_ca2Gi3kHtJrpHhR4_3Ab7KU046-p0dF5bVLLhYh3HEg-71R0tO9eytzbHkMZMY353aKF0bUqK4UrKnstDT55yo5j5oLpP0xGA9KGai6Kg
  db-messagelog:
    ports:
      - "0:5432"
