services:
  auxiliary-service:
    environment:
      # disabling jobs, will trigger them manually in tests
      - XROAD_AUXILIARY_SERVICE_MESSAGE_LOG_ARCHIVE_CRON=off
      - XROAD_AUXILIARY_SERVICE_MESSAGE_LOG_CLEAN_CRON=disabled
      # - XROAD_AUXILIARY_SERVICE_MESSAGE_LOG_ARCHIVE_CRON=*/2 * * * * ?
      # - XROAD_AUXILIARY_SERVICE_MESSAGE_LOG_CLEAN_CRON=*/3 * * * * ?
  message-log-cli:
    image: ${MESSAGE_LOG_ARCHIVER_IMG}
    entrypoint: [ "tail", "-f", "/dev/null" ]  # keep alive for test exec
    environment:
      #      - XROAD_HOST=message-log-cli
      - XROAD_SECRET_STORE_HOST=openbao
      - XROAD_SECRET_STORE_TOKEN=${XROAD_SECRET_STORE_TOKEN}
      - XROAD_SECRET_STORE_SCHEME=http
      - XROAD_COMMON_RPC_CHANNEL_CONFIGURATION_CLIENT_HOST=configuration-client
      - XROAD_DB_MESSAGELOG_HIBERNATE_CONNECTION_URL=jdbc:postgresql://db-messagelog:5432/messagelog
      - XROAD_DB_MESSAGELOG_HIBERNATE_CONNECTION_DRIVER_CLASS=org.postgresql.Driver
      - XROAD_DB_MESSAGELOG_HIBERNATE_CONNECTION_USERNAME=messagelog
      - XROAD_DB_MESSAGELOG_HIBERNATE_CONNECTION_PASSWORD=secret
      - XROAD_MESSAGE_LOG_ARCHIVER_CLEAN_KEEP_RECORDS_FOR=0
    networks:
      - xrd-ss-network
    ports:
      - "0:9999" # debug
    depends_on:
      db-messagelog-init:
        condition: service_completed_successfully
      openbao:
        condition: service_healthy
