services:
  proxy:
    environment:
      - XROAD_PROXY_MESSAGE_LOG_TIMESTAMPER_TIMESTAMP_IMMEDIATELY=true
      - XROAD_PROXY_DSP_SERVERPROXY_ENDPOINT=https://${DSP_PARTICIPANT_ID:-xrd-ss}:5500
      - XROAD_COMMON_GLOBAL_CONF_REFRESH_RATE=10S
  configuration-client:
    environment:
      - XROAD_CONFIGURATION_CLIENT_UPDATE_INTERVAL=10
  ui:
    environment:
      - XROAD_PROXY_UI_API_DATASPACE_ENABLED=true
      - XROAD_PROXY_UI_API_DATASPACE_IDENTITY_HUB_URL=https://${ENV_PREFIX:-}ds-identity-hub:7182
      - XROAD_PROXY_UI_API_DATASPACE_CONTROL_PLANE_URL=https://${ENV_PREFIX:-}ds-control-plane:8182
      - XROAD_PROXY_UI_API_DATASPACE_PARTICIPANT_ID=${DSP_PARTICIPANT_ID:-xrd-ss}
      - XROAD_PROXY_UI_API_DATASPACE_MANAGEMENT_CONTEXT_ENABLED=${DSP_MGMT_CONTEXT:-false}
      - XROAD_PROXY_UI_API_DATASPACE_ISSUER_DID=did:web:cs%3A6183:issuer
      - XROAD_PROXY_UI_API_DATASPACE_IDENTITY_TOKEN=eyJraWQiOiI3NGYzNDIyYjM3ZmM4Njg4ZTdmNWE3NDE2MjdmODg4OSIsInR5cCI6ImF0K2p3dCIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJ0ZXN0LWlzc3VlciIsImV4cCI6MjAwNDI2ODkwMCwiaWF0IjoxNzgzNTE2OTAwLCJqdGkiOiI3NDcyYmExN2ExMjE0MGI3YWVhNjNlNDM2ZWI1OTMxMSIsInNjb3BlIjoiaWRlbnRpdHktYXBpOmFkbWluIn0.LTjYT366IgFiI12rkxBatvzoIbtTzoYYVXRE9ytAJ23thT_cVid6Gv3m7XKe6bEphARXodhJqTwxeLYMtHAI_XIIC50xZ76e2mo9qLF9LX3JR2_Y5prMDb1BjmYpzedLupnu8SwB2W9n7POYeaMMTTXDlCZsqR2zffwZaCliXGWuj9VLdp0SUvNc8Xz9LMR1C0NNwL-HSH0oBHzMTn0E7kFSJ5HU0AZNa-h9ZNpYu6e4S_Yx7Lo4xRFtVMFRCW8sqfWfqjE861DVGTaQKgmBerbA0jfgaOWB4IU_8EwPBse68N2w8rCUJ4NU6MgRpd8uKEAbSBwNCmSpBvOOriqqAw
      - XROAD_PROXY_UI_API_DATASPACE_CONTROL_PLANE_TOKEN=eyJraWQiOiI3NGYzNDIyYjM3ZmM4Njg4ZTdmNWE3NDE2MjdmODg4OSIsInR5cCI6ImF0K2p3dCIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJ0ZXN0LWlzc3VlciIsImV4cCI6MjAwNDI2ODkwMCwiaWF0IjoxNzgzNTE2OTAwLCJqdGkiOiJjZWI1MjYzM2M1YjU0MDU3OWM3OTIxZTRmN2QyOWM3NSIsInNjb3BlIjoibWFuYWdlbWVudC1hcGk6YWRtaW4ifQ.iNTzn9fdrEkO5SChx8d9aZI34kKW7HV6EfUauPHUs_HC7OpGXMra9qLaEUwcNVmaPdIp7qypBG-wgIEn9znZ6inhDI7V4hoGVTEE7bZS2jar5LTcnr_tt-7Y-frV7GX-qW-b-C9y7hDWpTE_D4mPCLXvhSPjKYAS3_ZP2uCryQ6wGyFUToyf39YDnMOys2vpkI9knnCDfdFFoPsLmVWAz7CWjtV5J_IpTwRP2c63trsPVuPn85tQqXIDI8-geiXmxUVGWFGQQSkCyHX3xSbFE0vC23HFFxkmV0EUr8qFS6wDNiSFw2UYmYfWgfMk64xRY3d07HFbAWwgYa4tZixT6Q
  db-messagelog:
    ports:
      - "0:5432"
