
Simple depenency and building instructions on Ubuntu 14.04:

0. Once for installing system depenencies on clean building host:

   sh SOURCE_DIR/doc/prepare_buildhost.sh

1. Update/install software depenencies in SOURCE_DIR:

   ./update_ruby_dependencies.sh

   Its needed only when system dependencies are renewed.

2. Build software and Ubuntu packages in SOURCE_DIR:

   ./build_packages.sh

Built packages are in SOURCE_DIR/packages

