---
- name: configure remote database
  block:
    - name: install remote database package
      apt:
        name: xroad-database-remote
        state: latest

    - name: xroad.properties template
      template:
        src: "xroad.properties"
        dest: "/etc/xroad.properties"
        owner: "root"
        group: "root"
        mode: "0600"
        force: no

  when: database_admin_password is defined and database_admin_password != ""

- name: debconf xroad-confproxy
  debconf:
    name: xroad-confproxy
    question: "{{ item.question }}"
    vtype: string" # parametrize if you add a different type of question to item list
    value: "{{ item.value }}"
  with_items:
    - { question: "xroad-common/database-host", value: "{{ database_host }}" }
  when: database_host is defined and database_host != ""
  tags:
    - install-xroad-cp-packages

- name: ensure postgres password is present in xroad.properties
  lineinfile:
    path: /etc/xroad.properties
    regexp: '^postgres\.connection\.password\s*='
    line: "postgres.connection.password = {{ database_admin_password }}"
    create: yes
    owner: root
    group: root
    mode: "0600"
  when: database_admin_password is defined and database_admin_password != ""

- name: install xroad-confproxy via apt
  apt:
    name: xroad-confproxy
    state: latest
    force: yes
  tags:
    - install-xroad-cp-packages