---
- name: configure remote database
  block:
    - name: install remote database package
      apt:
        name: xroad-database-remote
        state: latest

    - name: xroad.properties template
      template:
        src: "xroad.properties"
        dest: "/etc/xroad.properties"
        owner: "root"
        group: "root"
        mode: 0600
        force: no

    - name: debconf xroad-confproxy
      debconf:
        name: xroad-confproxy
        question: "{{ item.question }}"
        vtype: "string"
        value: "{{ item.value }}"
      with_items:
        - { question: "xroad-common/database-host", value: "{{ database_host }}" }

    - name: create xroad properties file
      copy:
        content: "postgres.connection.password = {{ database_admin_password }}"
        dest: /etc/xroad.properties
        mode: 0600

  when:
    - database_admin_password is defined
    - database_admin_password != ""
    - database_host is defined
    - database_host != ""

- name: "install xroad-confproxy via apt"
  apt:
    name: xroad-confproxy
    state: latest
    force: yes
  tags:
    - install-xroad-cp-packages