services:
  openbao:
    image: ${OPENBAO_DEV_IMG}
    pull_policy: always
    environment:
      - BAO_ADDR=http://0.0.0.0:8200
      - BAO_TOKEN=${XROAD_SECRET_STORE_ROOT_TOKEN}
      - XROAD_SECRET_STORE_TOKEN_OVERRIDE=${XROAD_SECRET_STORE_TOKEN:-}
    healthcheck:
      interval: 5s
      retries: 40
      test: [ "CMD", "sh", "-c", "bao secrets list -format=json | jq 'has(\"xrd-pki/\")' | grep -q true" ]
    deploy:
      resources:
        reservations:
          memory: 64M
        limits:
          memory: 256M
  op-monitor:
    image: ${OP_MONITOR_IMG}
    pull_policy: always
    environment:
      - XROAD_HOST=op-monitor
      - XROAD_SECRET_STORE_HOST=openbao
      - XROAD_SECRET_STORE_TOKEN=${XROAD_SECRET_STORE_TOKEN}
      - XROAD_SECRET_STORE_SCHEME=http
      - XROAD_COMMON_RPC_USE_TLS=false
      - XROAD_COMMON_GLOBAL_CONF_SOURCE=FILESYSTEM
      - XROAD_OP_MONITOR_RPC_LISTEN_ADDRESS=0.0.0.0
      - XROAD_DB_OP_MONITOR_HIBERNATE_CONNECTION_URL=jdbc:postgresql://db-opmonitor:5432/op-monitor
      - XROAD_DB_OP_MONITOR_HIBERNATE_CONNECTION_USERNAME=opmonitor
      - XROAD_DB_OP_MONITOR_HIBERNATE_CONNECTION_PASSWORD=secret
      - XROAD_DB_OP_MONITOR_HIBERNATE_CONNECTION_DRIVER_CLASS=org.postgresql.Driver
    ports:
      - "0:9999" # debug port
    healthcheck:
      interval: 5s
      retries: 40
      test: [ "CMD", "curl", "-f", "-k", "http://localhost:4099/q/health" ]
    depends_on:
      db-opmonitor-init:
        condition: service_completed_successfully
    deploy:
      resources:
        reservations:
          memory: 96M
        limits:
          memory: 512M
    volumes:
      - ./container-files/etc/xroad:/etc/xroad
  db-opmonitor:
    image: postgres:17
    environment:
      - POSTGRES_DB=op-monitor
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=opmonitor
    ports:
      - "0:5432"
    healthcheck:
      start_period: 5s
      interval: 5s
      retries: 40
      test: [ "CMD", "sh", "-c", "pg_isready -U opmonitor -d op-monitor -h localhost" ]
    deploy:
      resources:
        reservations:
          memory: 64M
        limits:
          memory: 256M
  db-opmonitor-init:
    build:
      context: .
      dockerfile: db-init.dockerfile
      args:
        - DB_INIT_IMG=${DB_INIT_IMG}
    environment:
      - JDBC_URL=jdbc:postgresql://db-opmonitor:5432/op-monitor
      - JDBC_USER=opmonitor
      - JDBC_PASSWORD=secret
      - CHANGELOG=op-monitor-int-test
      - DEFAULT_SCHEMA_NAME=public
      - PROP_DB_USER=opmonitor
      - LIQUIBASE_CONTEXTS=int-test
    depends_on:
      db-opmonitor:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          memory: 64M
        limits:
          memory: 512M
