#!/bin/bash

die () {
    echo >&2 "$@"
    exit 1
}


if [ "$(id -nu )" != "sdsb" ]
then
 die "ABORTED. This script must run under sdsb user "
fi

. /etc/sdsb/services/confproxy.conf

UTIL_CP="/usr/share/sdsb/jlib/configuration-proxy.jar"

${JAVA_HOME}/bin/java ${SDSB_PARAMS} ${CONFPROXY_PARAMS} -cp ${UTIL_CP} \
ee.cyber.sdsb.confproxy.commandline.ConfProxyUtilMain ee.cyber.sdsb.confproxy.commandline.ConfProxyUtilAddSigningKey $@

