---
argument_specs:
  main:
    short_description: Deploy X-Road Security Server stack
    options:
      security_server_namespace: {type: str, required: true}
      kubeconfig_path: {type: path, required: true}
      security_server_chart_repo: {type: str, required: false}
      security_server_chart: {type: str, required: true}
      security_server_chart_version: {type: str, required: false}
      postgres_image: {type: str, required: true}
      xroad_image_registry: {type: str, required: false}
      xroad_image_tag: {type: str, required: false}
      serverconf_init_image: {type: str, required: false}
      jvm_metrics_enabled: {type: bool, default: false}
      openbao_tls_secret_name: {type: str, default: openbao-server-tls}
      configuration_client_update_interval: {type: str, default: "10"}
      proxy_dsp_enabled: {type: bool, default: true}
      ss2_advertised_host: {type: str, required: false}
      trusted_issuer_host: {type: str, default: xrd-cs}
      xrd_ca_external_host: {type: str, default: xrd-ca.lxd}
      serverconf_db: {type: dict, required: true}
      messagelog_db: {type: dict, required: true}
      opmonitor_db: {type: dict, required: true}
      ds_control_plane_db: {type: dict, required: true}
      ds_identity_hub_db: {type: dict, required: true}
      ds_issuer_service_db: {type: dict, required: true}
