#!/bin/bash

die () {
    echo >&2 "$@"
    exit 1
}


if [ "$(id -nu )" != "xroad" ]
then
 die "ABORTED. This script must run under xroad user "
fi

JAR="/opt/app/cli/quarkus-run.jar"

XROAD_CONFPROXY_CLI_PARAMS="-XX:+UseG1GC -Xmx50m -XX:+ExitOnOutOfMemoryError -Dquarkus.profile=cli,containerized -Dfile.encoding=UTF-8 ${XROAD_CONFPROXY_CLI_PARAMS}"

java ${XROAD_CONFPROXY_CLI_PARAMS} ${XROAD_PARAMS} -jar ${JAR} $@
