FROM eclipse-temurin:21-jre

RUN groupadd --system --gid 999 xroad && \
    useradd --system  \
    --uid 999  \
    --no-create-home \
    --shell /usr/sbin/nologin  \
    --gid xroad xroad

RUN mkdir /var/log/xroad && \
    mkdir /var/lib/xroad && \
    mkdir /var/tmp/xroad && \
    mkdir /var/cache/xroad && \
#    mkdir /opt/app/cache && \
    mkdir -p /etc/xroad/ssl && \
    mkdir -p /etc/xroad/globalconf && \
#    chown -R xroad:xroad /optapp && \
    chown -R xroad:xroad /var/log/xroad && \
    chown -R xroad:xroad /var/lib/xroad && \
    chown -R xroad:xroad /var/tmp/xroad && \
    chown -R xroad:xroad /var/cache/xroad && \
    chown -R xroad:xroad /etc/xroad

COPY build/LICENSE.txt /opt/app/LICENSE.txt
COPY build/3RD-PARTY-NOTICES.txt /opt/app/3RD-PARTY-NOTICES.txt