source 'https://rubygems.org'

gem 'activerecord-jdbcpostgresql-adapter', '~>1.3.25'
gem 'jdbc-postgres', '~>9.4'

if File.exists?("vendor/engines/common-ui")
    gem 'common-ui', :path => "vendor/engines/common-ui"
else
    gem 'common-ui', :path => "../common-ui"
end

if File.exists?("vendor/engines/center-common")
  gem 'center-common', :path => "vendor/engines/center-common"
else
  gem 'center-common', :path => "../center-common"
end

if ENV["RAILS_ENV"] != "production"
  group :test do
    gem 'jdbc-sqlite3', '~>3.7.2.1'
    gem 'activerecord-jdbcsqlite3-adapter', '~>1.3.25'
  end
end
