/*
 * The MIT License
 *
 * Copyright (c) 2019- Nordic Institute for Interoperability Solutions (NIIS)
 * Copyright (c) 2018 Estonian Information System Authority (RIA),
 * Nordic Institute for Interoperability Solutions (NIIS), Population Register Centre (VRK)
 * Copyright (c) 2015-2017 Estonian Information System Authority (RIA), Population Register Centre (VRK)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/**
 * ### agent — 2026-06-12
 *
 * Tool decision — spec-bound handler approach:
 *
 * **Chosen: `openapi-msw` + `openapi-typescript` (for `paths`) + AJV (runtime body validation)**
 *
 * `openapi-msw` wraps MSW with a `createOpenApiHttp<paths>()` factory that types every handler
 * against the OpenAPI `paths` interface: unknown path, wrong HTTP method, or forbidden status
 * code fails `tsc`. The `paths` interface is generated by `openapi-typescript` (separate CLI from
 * `@hey-api/openapi-ts`) off the same YAML source. AJV validates response body shapes at runtime
 * so a drifted fixture fails the test, not just `tsc`.
 *
 * **Rejected alternatives:**
 * - *Hand-typed handlers* (prior state): types guard shape only; nothing rejects a forbidden
 *   status; body drift is silent.
 * - *`@hey-api/openapi-ts` v0.97 plugins alone*: that version does not expose an MSW or Zod
 *   plugin; no `paths` interface is generated.
 * - *Custom codegen on top of `@hey-api/openapi-ts`*: re-invents what `openapi-msw` already does,
 *   adding maintenance surface with no benefit.
 *
 * **Non-spec endpoints** (`/api/v1/notifications/session-status` and `/api/v1/notifications/alerts`)
 * are not defined in the OpenAPI spec (`openapi-definition.yaml`). They are Spring MVC controllers
 * in `common-admin-api` with no YAML spec. Handlers for these use MSW's untyped `http` wrapper
 * from `specHttp.untyped`, with AJV validation against inline schemas derived from the Java domain
 * objects. Fixture values are taken from the Java `AlertData` and `StatusData` records.
 *
 * **Fixtures:** `clients.json` and `service-description-created.json` have real shape and are
 * schema-valid; their values are synthetic. Run `capture.sh` against a live Security Server stack
 * to replace synthetic values with real backend responses when a stack is available.
 */

import { HttpResponse } from 'msw';
import { specHttp, validateBody } from './spec-http';
import type { Client, ServiceDescription } from '@/openapi-types';

import clientsGolden from './golden/clients.json';
import serviceDescriptionCreatedGolden from './golden/service-description-created.json';

// ── JSON Schema definitions (inlined from OpenAPI components/schemas) ────────

const clientSchema = {
  type: 'object',
  required: ['member_class', 'member_code'],
  properties: {
    id: { type: 'string' },
    instance_id: { type: 'string' },
    member_name: { type: 'string' },
    member_class: { type: 'string' },
    member_code: { type: 'string' },
    subsystem_code: { type: 'string' },
    owner: { type: 'boolean' },
    has_valid_local_sign_cert: { type: 'boolean' },
    connection_type: { type: 'string', enum: ['HTTP', 'HTTPS', 'HTTPS_NO_AUTH'] },
    status: { type: 'string', enum: ['REGISTERED', 'SAVED', 'GLOBAL_ERROR', 'REGISTRATION_IN_PROGRESS', 'DELETION_IN_PROGRESS'] },
  },
};

const serviceSchema = {
  type: 'object',
  required: ['id', 'service_code', 'url', 'timeout', 'service_description_id', 'client_id'],
  properties: {
    id: { type: 'string' },
    service_description_id: { type: 'string' },
    client_id: { type: 'string' },
    service_code: { type: 'string' },
    full_service_code: { type: 'string' },
    timeout: { type: 'integer' },
    ssl_auth: { type: 'boolean' },
    url: { type: 'string' },
  },
};

const tokenCertificateSchema = {
  type: 'object',
  required: ['ocsp_status', 'owner_id', 'active', 'saved_to_configuration', 'certificate_details', 'status'],
  properties: {
    ocsp_status: { type: 'string' },
    owner_id: { type: 'string' },
    active: { type: 'boolean' },
    saved_to_configuration: { type: 'boolean' },
    certificate_details: { type: 'object' },
    status: { type: 'string' },
  },
};

const serviceDescriptionSchema = {
  type: 'object',
  required: ['id', 'url', 'type', 'disabled', 'disabled_notice', 'refreshed_at', 'services', 'client_id'],
  properties: {
    id: { type: 'string' },
    url: { type: 'string' },
    type: { type: 'string', enum: ['WSDL', 'REST', 'OPENAPI3'] },
    disabled: { type: 'boolean' },
    disabled_notice: { type: 'string' },
    refreshed_at: { type: 'string', format: 'date-time' },
    services: { type: 'array', items: serviceSchema },
    client_id: { type: 'string' },
  },
};

const alertsResponseSchema = {
  type: 'object',
  required: ['global_conf_valid', 'soft_token_pin_entered', 'current_time', 'certificate_renewal_job_success', 'auth_certificate_ids_with_errors', 'sign_certificate_ids_with_errors'],
  properties: {
    current_time: { type: 'string' },
    backup_restore_running_since: { type: 'string', nullable: true },
    global_conf_valid: { type: 'boolean' },
    soft_token_pin_entered: { type: 'boolean' },
    certificate_renewal_job_success: { type: 'boolean' },
    auth_certificate_ids_with_errors: { type: 'array', items: { type: 'string' } },
    sign_certificate_ids_with_errors: { type: 'array', items: { type: 'string' } },
  },
};

const sessionStatusSchema = {
  type: 'object',
  required: ['valid'],
  properties: {
    valid: { type: 'boolean' },
  },
};

// ── Golden fixture values ─────────────────────────────────────────────────────

export const clientsFixture = clientsGolden as Client[];
export const subsystemClientFixture = clientsGolden[1] as Client;
export const createdServiceDescriptionFixture = serviceDescriptionCreatedGolden as ServiceDescription;
export const serviceDescriptionFixture = serviceDescriptionCreatedGolden as ServiceDescription;

// ── Eager fixture validation (runs at module load time) ───────────────────────
//
// Validation throws during module initialisation rather than inside a Service
// Worker handler. A browser-mode SW handler runs in a separate thread; a throw
// there is swallowed by MSW and never reaches the test runner. Validating at
// import time means a drifted fixture surfaces as a module-load error — the
// test that imports this module fails immediately with the AJV message.

validateBody({ type: 'array', items: clientSchema }, clientsFixture);
validateBody(serviceDescriptionSchema, createdServiceDescriptionFixture);
validateBody({ type: 'array', items: tokenCertificateSchema }, []);

const _alertsBody = {
  current_time: new Date().toISOString(),
  global_conf_valid: true,
  soft_token_pin_entered: true,
  certificate_renewal_job_success: true,
  auth_certificate_ids_with_errors: [],
  sign_certificate_ids_with_errors: [],
};
validateBody(alertsResponseSchema, _alertsBody);
validateBody(sessionStatusSchema, { valid: true });

// ── Spec-bound handlers ───────────────────────────────────────────────────────

export const handlers = [
  specHttp.get('/clients', ({ response }) => {
    return response(200).json(clientsFixture);
  }),

  specHttp.get('/clients/{id}', ({ params, response }) => {
    const id = decodeURIComponent(params.id as string);
    const client = clientsFixture.find((c) => c.id === id) ?? subsystemClientFixture;
    return response(200).json(client);
  }),

  specHttp.get('/clients/{id}/sign-certificates', ({ response }) => {
    return response(200).json([]);
  }),

  specHttp.get('/clients/{id}/service-descriptions', ({ response }) => {
    return response(200).json([]);
  }),

  specHttp.post('/clients/{id}/service-descriptions', ({ response }) => {
    return response(201).json(createdServiceDescriptionFixture);
  }),

  // Non-spec endpoints: use specHttp.untyped (these controllers are not in openapi-definition.yaml)
  specHttp.untyped.get('/api/v1/notifications/session-status', () => {
    return HttpResponse.json({ valid: true });
  }),

  specHttp.untyped.get('/api/v1/notifications/alerts', () => {
    return HttpResponse.json(_alertsBody);
  }),
];
