#!/bin/bash
# Writes the dev/test dataspace TLS certificate and key — already generated by the
# ds-https-keystore-init step and mounted read-only at /etc/xroad/ds-ssl — into
# OpenBao at tls/ds-https, so the co-located Issuer Service's owned Jetty module
# (which reads the certificate from OpenBao, not from a file) has something to serve.
#
# Stopgap: retires once the DS TLS certificate is enrolled via ACME or the manual
# CSR flow instead of this dev-only recipe (XRDDEV-3294). If no dev keystore is
# mounted, this is a no-op — the Issuer Service then fails closed on boot with an
# actionable "no DS TLS certificate provisioned" error, as designed.
set -euo pipefail

CERT_FILE="/etc/xroad/ds-ssl/ds-https-cert.pem"
KEY_FILE="/etc/xroad/ds-ssl/ds-https-key.pem"
TOKEN_FILE="/etc/xroad/secret-store-client-token"
BAO_ADDR="${BAO_ADDR:-https://127.0.0.1:8200}"

if [ ! -f "$CERT_FILE" ] || [ ! -f "$KEY_FILE" ]; then
  echo "[ds-https-vault-seed] No dev dataspace TLS certificate/key at /etc/xroad/ds-ssl; skipping vault seed" >&2
  exit 0
fi

TOKEN=$(cat "$TOKEN_FILE")
PAYLOAD=$(jq -n --rawfile cert "$CERT_FILE" --rawfile key "$KEY_FILE" '{certificate: $cert, privateKey: $key}')

attempt=0
max_attempts=5
until curl -fsSk -X POST \
  -H "X-Vault-Token: ${TOKEN}" \
  -H "Content-Type: application/json" \
  --data "$PAYLOAD" \
  "${BAO_ADDR}/v1/xrd-secret/tls/ds-https" >/dev/null; do
  attempt=$((attempt + 1))
  if [ "$attempt" -ge "$max_attempts" ]; then
    echo "[ds-https-vault-seed] Failed to write DS TLS certificate to OpenBao after ${max_attempts} attempts" >&2
    exit 1
  fi
  echo "[ds-https-vault-seed] OpenBao not ready yet, retrying ($attempt/$max_attempts)..." >&2
  sleep 2
done

echo "[ds-https-vault-seed] Wrote dev dataspace TLS certificate to OpenBao at tls/ds-https"
