#!/bin/bash

die () {
    echo >&2 "$@"
    exit 1
}


if [ "$(id -nu )" != "xroad" ]
then
 die "ABORTED. This script must run under xroad user "
fi

. /etc/xroad/services/confproxy.conf

UTIL_CP="/usr/share/xroad/jlib/configuration-proxy.jar"

${JAVA_HOME}/bin/java ${XROAD_PARAMS} ${CONFPROXY_PARAMS} -cp ${UTIL_CP} \
ee.ria.xroad.confproxy.commandline.ConfProxyUtilMain ee.ria.xroad.confproxy.commandline.ConfProxyUtilAddSigningKey $@

