/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ee_ria_xroad_common_util_MemoryPasswordStoreProvider */

#ifndef _Included_ee_ria_xroad_common_util_MemoryPasswordStoreProvider
#define _Included_ee_ria_xroad_common_util_MemoryPasswordStoreProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ee_ria_xroad_common_util_MemoryPasswordStoreProvider
 * Method:    read
 * Signature: (ILjava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ee_ria_xroad_common_util_MemoryPasswordStoreProvider_read
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     ee_ria_xroad_common_util_MemoryPasswordStoreProvider
 * Method:    write
 * Signature: (Ljava/lang/String;ILjava/lang/String;[BI)V
 */
JNIEXPORT void JNICALL Java_ee_ria_xroad_common_util_MemoryPasswordStoreProvider_write
  (JNIEnv *, jclass, jstring, jstring, jbyteArray, jint);

/*
 * Class:     ee_ria_xroad_common_util_MemoryPasswordStoreProvider
 * Method:    clear
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ee_ria_xroad_common_util_MemoryPasswordStoreProvider_clear
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
