#!/bin/bash

# Please do not change this file! It will be overwritten by updates.
# System specific changes should be added to /etc/xroad/services/local.properties

. /etc/xroad/services/global.conf

export OTEL_SERVICE_NAME=xroad-opmonitor${XROAD_NODE_ID:+-${XROAD_NODE_ID}}

XROAD_OPMON_PARAMS=" ${XROAD_OTEL_PARAMS} -Xms50m -Xmx350m -XX:MaxMetaspaceSize=120m \
-Dquarkus.profile=${XROAD_QUARKUS_PROFILES} $XROAD_OPMON_PARAMS"

apply_local_conf XROAD_OPMON_PARAMS
