container_ports:
  http_cp:
    connect: "tcp:127.0.0.1:80"
    listen: "tcp:0.0.0.0:{{ 3710 + (groups['cp_servers'].index(inventory_hostname) * 100) }}"
    type: proxy
  https_cp:
    connect: "tcp:127.0.0.1:443"
    listen: "tcp:0.0.0.0:{{ 3715 + (groups['cp_servers'].index(inventory_hostname) * 100) }}"
    type: proxy
  database_cp:
    connect: "tcp:127.0.0.1:5432"
    listen: "tcp:0.0.0.0:{{ 3720 + (groups['cp_servers'].index(inventory_hostname) * 100) }}"
    type: proxy
  api_cp:
    connect: "tcp:127.0.0.1:4000"
    listen: "tcp:0.0.0.0:{{ 3700 + (groups['cp_servers'].index(inventory_hostname) * 100) }}"
    type: proxy
  app_debug:
    connect: "tcp:127.0.0.1:9950"
    listen: "tcp:0.0.0.0:{{ 3790 + (groups['cp_servers'].index(inventory_hostname) * 100) }}"
    type: proxy