../../../../src/xroad/common/secret-store-local/usr/share/xroad/scripts/* usr/share/xroad/scripts
../../../../../.scripts/configure-mirror-openbao-deb.sh usr/share/xroad/scripts/configure-mirror-openbao.sh
../../../../src/xroad/common/secret-store-local/etc/* etc/
../../../../../../src/LICENSE.txt usr/share/doc/xroad-secret-store-local/
../../../../../../src/3RD-PARTY-NOTICES.txt usr/share/doc/xroad-secret-store-local/
