../../../../src/xroad/common/message-log-archiver/etc/* etc/
../../../../src/xroad/common/message-log-archiver/usr/* usr/
../../../../../../src/service/message-log-archiver/message-log-archiver-cli/build/quarkus-app/* usr/share/xroad/jlib/message-log-archiver/
../../../../../../src/LICENSE.txt usr/share/doc/xroad-message-log-archiver/
../../../../../../src/3RD-PARTY-NOTICES.txt usr/share/doc/xroad-message-log-archiver
../../../../../../CHANGELOG.md usr/share/doc/xroad-message-log-archiver
