../../../../src/xroad/common/addon/proxy/messagelog-archiver.conf etc/xroad/services/
../../../../src/xroad/common/addon/proxy/xroad-messagelog-archiver usr/share/xroad/bin/
../../../../../../src/service/message-log-archiver/message-log-archiver-application/scripts/archive-http-transporter.sh usr/share/xroad/scripts/
../../../../../../src/service/message-log-archiver/message-log-archiver-application/build/quarkus-app/* usr/share/xroad/jlib/addon/proxy/messagelog-archiver/

../../../../src/xroad/default-configuration/addons/message-log.ini etc/xroad/conf.d/addons/

../../../../../../src/addons/messagelog/messagelog-db/src/main/resources/liquibase/messagelog-changelog.xml usr/share/xroad/db/
../../../../../../src/addons/messagelog/messagelog-db/src/main/resources/liquibase/messagelog/ usr/share/xroad/db/
../../../../src/xroad/common/addon/proxy/setup_messagelog_db.sh usr/share/xroad/scripts/

../../../../../../src/service/message-log-archiver/message-log-archiver-application/scripts/demo-upload.pl usr/share/doc/xroad-addon-messagelog/archive-server/
../../../../../../src/addons/messagelog/messagelog-archive-verifier/build/libs/messagelog-archive-verifier.jar usr/share/doc/xroad-addon-messagelog/archive-hashchain-verifier/
../../../../../../src/addons/messagelog/messagelog-archive-verifier/README.md usr/share/doc/xroad-addon-messagelog/archive-hashchain-verifier/

../../../../../../src/tool/asic-verifier-cli/build/libs/asicverifier.jar usr/share/xroad/jlib/
../../../../../../src/LICENSE.txt usr/share/doc/xroad-addon-messagelog/
../../../../../../src/3RD-PARTY-NOTICES.txt usr/share/doc/xroad-addon-messagelog/
../../../../../../CHANGELOG.md usr/share/doc/xroad-addon-messagelog/
