../../../../src/xroad/common/op-monitor/etc/* etc
../../../../src/xroad/common/op-monitor/usr/* usr
../../../../../../src/service/op-monitor/op-monitor-db/src/main/resources/liquibase/* usr/share/xroad/db/

../../../../../../src/service/op-monitor/op-monitor-application/build/quarkus-app/* usr/share/xroad/jlib/op-monitor/

../../../../../../src/LICENSE.txt usr/share/doc/xroad-opmonitor
../../../../../../src/3RD-PARTY-NOTICES.txt usr/share/doc/xroad-opmonitor
../../../../../../CHANGELOG.md usr/share/doc/xroad-opmonitor
