../../../../src/xroad/common/backup-manager/etc/* etc/
../../../../src/xroad/common/backup-manager/usr/* usr/
../../../../../../src/service/backup-manager/backup-manager-application/build/quarkus-app/* usr/share/xroad/jlib/backup-manager/
../../../../../../src/LICENSE.txt usr/share/doc/xroad-backup-manager/
../../../../../../src/3RD-PARTY-NOTICES.txt usr/share/doc/xroad-backup-manager
../../../../../../CHANGELOG.md usr/share/doc/xroad-backup-manager
