../../../../src/xroad/common/auxiliary-service/etc/* etc/
../../../../src/xroad/common/auxiliary-service/usr/* usr/
../../../../../../src/service/auxiliary-service/auxiliary-service-application/build/quarkus-app/* usr/share/xroad/jlib/auxiliary-service/
../../../../../../src/LICENSE.txt usr/share/doc/xroad-auxiliary-service/
../../../../../../src/3RD-PARTY-NOTICES.txt usr/share/doc/xroad-auxiliary-service
../../../../../../CHANGELOG.md usr/share/doc/xroad-auxiliary-service
