../../../../src/xroad/common/confproxy/etc/* etc/
../../../../../../src/service/configuration-proxy/configuration-proxy-application/scripts/* usr/share/xroad/scripts
../../../../../../src/service/configuration-proxy/configuration-proxy-application/build/libs/configuration-proxy-1.0.jar usr/share/xroad/jlib/
../../../../src/xroad/default-configuration/confproxy.ini etc/xroad/conf.d
../../../../src/xroad/default-configuration/confproxy-logback.xml etc/xroad/conf.d
../../../../../../src/3RD-PARTY-NOTICES.txt usr/share/doc/xroad-confproxy
../../../../../../CHANGELOG.md usr/share/doc/xroad-confproxy
