FROM eclipse-temurin:21-jre

WORKDIR /opt/app

RUN \
      --mount=type=cache,target=/var/cache/apt,sharing=locked \
      --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get -qq update &&  \
    apt-get install --no-install-recommends -qq -y gnupg

RUN groupadd --system --gid 999 xroad && \
    useradd --system --uid 999 --no-create-home --shell /usr/sbin/nologin --gid xroad xroad

#TODO XRDDEV-2755 temporary users for PAM based auth
RUN usermod --append -G shadow xroad && \
    groupadd --system xroad-system-administrator && \
    groupadd --system xroad-security-officer && \
    groupadd --system xroad-registration-officer && \
    groupadd --system xroad-service-administrator && \
    groupadd --system xroad-securityserver-observer && \
    useradd -m xrd -s /usr/sbin/nologin -p '$6$JeOzaeWnLAQSUVuO$GOJ0wUKSVQnOR4I2JgZxdKr.kMO.YGS21SGaAshaYhayv8kSV9WuIFCZHTGAX8WRRTB/2ojuLnJg4kMoyzpcu1' && \
    usermod -a -G xroad-system-administrator xrd && \
    usermod -a -G xroad-security-officer xrd && \
    usermod -a -G xroad-registration-officer xrd && \
    usermod -a -G xroad-service-administrator xrd && \
    usermod -a -G xroad-securityserver-observer xrd

RUN mkdir /var/log/xroad && \
    mkdir /var/tmp/xroad/ && \
    mkdir /opt/app/cache && \
    mkdir -p /etc/xroad/ssl && \
    mkdir -p /etc/xroad/globalconf && \
    chown -R xroad:xroad /opt/app && \
    chown -R xroad:xroad /var/log/xroad && \
    chown -R xroad:xroad /var/tmp/xroad/ && \
    chown -R xroad:xroad /etc/xroad