### Test DSP proxy flow (UC3: negotiation + dataplane transfer)
POST http://{{host}}:{{proxy_port}}/r1/DEV/COM/1234/TestService/mock1
Content-Type: application/json
X-Road-Client: DEV/COM/4321/TestClient

{
  "data": 1.0,
  "service": "random"
}

> {%
    client.test("Response status is 200", function () {
        client.assert(response.status === 200, "Expected 200, got " + response.status);
    });
    client.test("Response contains greeting message", function () {
        client.assert(response.body.message === "Hello, world from POST service!",
            "Expected greeting message, got: " + response.body.message);
    });
%}
