#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

#require 'rake/testtask'

require File.expand_path('../config/application', __FILE__)

#namespace :test do
#  desc "Benchmark for XML read and write"
#  Rake::TestTask.new(:benchmark) do |t|
#    t.libs << "test"
#    t.pattern = 'test/benchmark/**/*_test.rb'
    # t.verbose = true
#  end
#end

#benchmark_task = Rake::Task["test:benchmark"]
#test_task = Rake::Task[:test]
#test_task.enhance { benchmark_task.invoke }

ProxyUi::Application.load_tasks
