configurableProperties:
  - propertyName: "xroad.proxy-ui-api.acme-certification-wait-attempts"
    defaultValue: "5"
    scope: "proxy-ui-api"
  - propertyName: "xroad.proxy-ui-api.acme-certification-wait-interval"
    defaultValue: "5"
    scope: "proxy-ui-api"

  - propertyName: "xroad.signer.selfsigned-cert-digest-algorithm"
    defaultValue: "SHA-512"
    scope: "signer"
  - propertyName: "xroad.signer.csr-signature-digest-algorithm"
    defaultValue: "SHA-256"
    scope: "signer"
  - propertyName: "xroad.signer.enforce-token-pin-policy"
    defaultValue: "false"
    scope: "signer"
  - propertyName: "xroad.signer.ocsp-response-retrieval-active"
    defaultValue: "false"
    scope: "signer"
  - propertyName: "xroad.signer.ocsp-retry-delay"
    defaultValue: "60"
    scope: "signer"
  - propertyName: "xroad.signer.ocsp-cache-path"
    defaultValue: "/var/cache/xroad/"
    scope: "signer"
  - propertyName: "xroad.signer.ocsp-prioritization-strategy"
    defaultValue: "NONE"
    scope: "signer"
  - propertyName: "xroad.signer.module-manager-update-interval"
    defaultValue: "60"
    scope: "signer"
  - propertyName: "xroad.signer.soft-token-rsa-sign-mechanism"
    defaultValue: "CKM_RSA_PKCS"
    scope: "signer"
  - propertyName: "xroad.signer.soft-token-ec-sign-mechanism"
    defaultValue: "CKM_ECDSA"
    scope: "signer"
  - propertyName: "xroad.signer.soft-token-pin-keystore-algorithm"
    defaultValue: "RSA"
    scope: "signer"
  - propertyName: "xroad.signer.key-length"
    defaultValue: "2048"
    scope: "signer"
  - propertyName: "xroad.signer.key-named-curve"
    defaultValue: "secp256r1"
    scope: "signer"

  - propertyName: "xroad.signer.autologin.enabled"
    defaultValue: "false"
    scope: "signer"
  - propertyName: "xroad.signer.autologin.retry.retry-delay"
    defaultValue: "3S"
    scope: "signer"
  - propertyName: "xroad.signer.autologin.retry.retry-exponential-backoff-multiplier"
    defaultValue: "1.0"
    scope: "signer"
  - propertyName: "xroad.signer.autologin.retry.retry-max-attempts"
    defaultValue: "20"
    scope: "signer"
  - propertyName: "xroad.signer.autologin.retry.retry-timeout"
    defaultValue: "60S"
    scope: "signer"

  - propertyName: "xroad.signer.addon.hwtoken.enabled"
    defaultValue: "false"
    scope: "signer"
  - propertyName: "xroad.signer.addon.hwtoken.session-pool-enabled"
    defaultValue: "false"
    scope: "signer"
  - propertyName: "xroad.signer.addon.hwtoken.session-pool-max-total"
    defaultValue: "10"
    scope: "signer"
  - propertyName: "xroad.signer.addon.hwtoken.session-pool-min-idle"
    defaultValue: "2"
    scope: "signer"
  - propertyName: "xroad.signer.addon.hwtoken.session-pool-max-idle"
    defaultValue: "5"
    scope: "signer"
  - propertyName: "xroad.signer.addon.hwtoken.session-acquire-timeout"
    defaultValue: "15S"
    scope: "signer"

  - propertyName: "xroad.signer.rpc.enabled"
    defaultValue: "true"
    scope: "signer"
  - propertyName: "xroad.signer.rpc.listen-address"
    defaultValue: "127.0.0.1"
    scope: "signer"
  - propertyName: "xroad.signer.rpc.port"
    defaultValue: "5560"
    scope: "signer"

  - propertyName: "xroad.signer.pin-hasher.iterations"
    defaultValue: "4"
    scope: "signer"
  - propertyName: "xroad.signer.pin-hasher.memory-kb"
    defaultValue: "19456"
    scope: "signer"
  - propertyName: "xroad.signer.pin-hasher.parallelism"
    defaultValue: "4"
    scope: "signer"
  - propertyName: "xroad.signer.pin-hasher.hash-length"
    defaultValue: "32"
    scope: "signer"

  - propertyName: "xroad.env-monitor.certificate-info-sensor-interval"
    defaultValue: "1d"
    scope: "monitor"
  - propertyName: "xroad.env-monitor.disk-space-sensor-interval"
    defaultValue: "60s"
    scope: "monitor"
  - propertyName: "xroad.env-monitor.exec-listing-sensor-interval"
    defaultValue: "60s"
    scope: "monitor"
  - propertyName: "xroad.env-monitor.system-metrics-sensor-interval"
    defaultValue: "5s"
    scope: "monitor"
  - propertyName: "xroad.env-monitor.limit-remote-data-set"
    defaultValue: "false"
    scope: "monitor"

  - propertyName: "xroad.env-monitor.rpc.enabled"
    defaultValue: "true"
    scope: "monitor"
  - propertyName: "xroad.env-monitor.rpc.listen-address"
    defaultValue: "127.0.0.1"
    scope: "monitor"
  - propertyName: "xroad.env-monitor.rpc.port"
    defaultValue: "2552"
    scope: "monitor"

  - propertyName: "xroad.auxiliary-service.backup.create-backup-metadata-path"
    defaultValue: "/usr/share/xroad/scripts/_create_backup_metadata.sh"
    scope: "auxiliary-service"
  - propertyName: "xroad.auxiliary-service.backup.backup-format-version-file-path"
    defaultValue: "/usr/share/xroad/scripts/_backup_format_version"
    scope: "auxiliary-service"

  - propertyName: "xroad.message-log-archiver.clean-transaction-batch-size"
    defaultValue: "10000"
    scope: "message-log-archiver"
  - propertyName: "xroad.message-log-archiver.clean-keep-records-for"
    defaultValue: "30"
    scope: "message-log-archiver"
  - propertyName: "xroad.message-log-archiver.max-filesize"
    defaultValue: "33554432"
    scope: "message-log-archiver"
  - propertyName: "xroad.message-log-archiver.transaction-batch-size"
    defaultValue: "10000"
    scope: "message-log-archiver"
  - propertyName: "xroad.message-log-archiver.archive-path"
    defaultValue: "/var/lib/xroad"
    scope: "message-log-archiver"
  - propertyName: "xroad.message-log-archiver.archive-transfer-command"
    defaultValue: ""
    scope: "message-log-archiver"
  - propertyName: "xroad.message-log-archiver.hash-algo-id"
    defaultValue: "SHA-512"
    scope: "message-log-archiver"

  - propertyName: "xroad.message-log-encryption.archive.encryption-enabled"
    defaultValue: "false"
  - propertyName: "xroad.message-log-encryption.archive.default-key-id"
    defaultValue: ""
  - propertyName: "xroad.message-log-encryption.archive.grouping-strategy"
    defaultValue: "NONE"

  - propertyName: "xroad.message-log-encryption.db.encryption-enabled"
    defaultValue: "false"
  - propertyName: "xroad.message-log-encryption.db.key-id"
    defaultValue: "default"
