configurableProperties:
  signer:
    - propertyName: "xroad.signer.client-timeout"
      defaultValue: "60000"
    - propertyName: "xroad.signer.ocsp-prioritization-strategy"
      defaultValue: "NONE"
  proxy:
    - propertyName: "xroad.proxy.client-timeout"
      defaultValue: "30000"
  common:
    - propertyName: "xroad.common.client-timeout"
      defaultValue: "30000"

