#!/bin/bash

# Please do not change this file! It will be overwritten by updates.
# System specific changes should be added to /etc/xroad/services/local.conf

. /etc/xroad/services/global.conf

export OTEL_SERVICE_NAME=xroad-messagelog-archiver${XROAD_NODE_ID:+-${XROAD_NODE_ID}}

XROAD_MESSAGE_LOG_ARCHIVER_PARAMS=" ${XROAD_OTEL_PARAMS} -Xmx200m -XX:MaxMetaspaceSize=90m -XX:+ExitOnOutOfMemoryError \
-Djava.util.logging.manager=org.jboss.logmanager.LogManager \
-Dquarkus.profile=${XROAD_QUARKUS_PROFILES} ${XROAD_MESSAGE_LOG_ARCHIVER_PARAMS}"

apply_local_conf XROAD_MESSAGE_LOG_ARCHIVER_PARAMS
