#!/bin/bash

if [ "$JAVA_HOME" = "" ]
then
	javabin="java"
else
	javabin="$JAVA_HOME/bin/java"
fi

classes=build/classes/test
classname=ee.ria.xroad.proxy.testsuite.ProxyTestSuite

if [ "$1" = "-proxy" ]
then
	shift
	classes=build/libs/proxy-1.0.jar
	classname=ee.ria.xroad.proxy.ProxyMain
fi

$javabin -Dxroad.proxy.ocspCachePath=build/ocsp-cache\
    -Dxroad.tempFiles.path=build/attach-tmp -Xmx2000m\
    -Dxroad.appLog.path=log\
    -Dxroad.proxy.globalConfFile=../systemtest/conf/local_test/globalconf.xml\
    -Dlogback.configurationFile=src/test/logback-proxytest.xml\
    -Dxroad.proxy.jetty-serverproxy-configuration-file=src/test/serverproxy.xml\
    -Dxroad.proxy.jetty-clientproxy-configuration-file=src/test/clientproxy.xml\
    -cp ../libs/hsqldb.jar:../common-test/build/libs/common-test-1.0.jar:build/libs/proxy-1.0.jar:../common-verifier/build/classes/test:$classes $classname $*
