#!/bin/bash

if [ "$JAVA_HOME" = "" ]
then
	javabin="java"
else
	javabin="$JAVA_HOME/bin/java"
fi

classes=build/classes/test
classname=ee.cyber.sdsb.proxy.testsuite.ProxyTestSuite

if [ "$1" = "-proxy" ]
then
	shift
	classes=build/libs/proxy-1.0.jar
	classname=ee.cyber.sdsb.proxy.ProxyMain
fi

$javabin -Dee.cyber.sdsb.secureLog.path=build/slog\
    -Dee.cyber.sdsb.proxy.ocspCachePath=build/ocsp-cache\
    -Dee.cyber.sdsb.tempFiles.path=build/attach-tmp -Xmx2000m\
    -Dee.cyber.sdsb.appLog.path=log\
    -Dee.cyber.sdsb.proxy.globalConfFile=../systemtest/conf/local_test/globalconf.xml\
    -Dee.cyber.sdsb.proxy.configurationFile=../systemtest/conf/local_test/serverconf_producer.xml\
    -cp ../common-test/build/libs/common-test-1.0.jar:build/libs/proxy-1.0.jar:$classes $classname $*
