#!/bin/bash

# set dataspaces enabled for poc.
crudini --set /etc/xroad/conf.d/local.ini dataspaces enabled true

exec java -Dedc.keystore="/etc/xroad-edc/certs/cert.pfx" \
    -Dedc.keystore.password=123456 \
    -Dedc.vault="/etc/xroad-edc/edc-vault.properties" \
    -Dedc.fs.config="/etc/xroad-edc/edc-configuration.properties" \
    -Xmx128m -jar /usr/share/xroad/jlib/connector.jar