
Simple depenency and building instructions on Ubuntu 14.04:

0. Once for installing system depenencies on clean building host:

   ./prepare_buildhost.sh

   Requires sudo execution permissions.

1. Update/install software depenencies:

   ./update_ruby_dependencies.sh

   Its needed only on first build or changelog states so.

2. Build software and Ubuntu packages in SOURCE_DIR:

   ./build_packages.sh


