xroad.common-rpc.use-tls=false
xroad.management-service.api-base-url=http://mock-server:1080
xroad.management-service.rate-limit-requests-per-second=100
xroad.management-service.rate-limit-requests-per-minute=1000
