---
- name: Check for EPEL repo
  stat:
    path: "/etc/yum.repos.d/epel.repo"
  register: epel

- name: EPEL repo key
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_facts['distribution_major_version'] }}

- name: Install EPEL repository
  dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
  when:
    - not epel.stat.exists

- name: X-Road repo key
  rpm_key:
    state: present
    key: "{{ rhel_repo_gpgkey }}"
  when:
    - rhel_repo_gpgkey is defined
    - package_source == "remote"
    - (rhel_repo_gpgcheck | default('no') | string | lower) in ['yes', 'true', '1']

- name: Setup the correct repository for X-Road installation
  yum_repository:
    name: "x-road"
    file: "xroad"
    description: "X-Road repository for RHEL{{ ansible_facts['distribution_major_version'] }}"
    baseurl: "{{ rhel_repo_baseurl }}"
    gpgcheck: "{{ rhel_repo_gpgcheck | default('no') }}"
    gpgkey: "{{ rhel_repo_gpgkey | default('') }}"
    repo_gpgcheck: "{{ rhel_repo_gpgcheck | default('no') }}"
    metadata_expire: "{{ rhel_repo_metadaexpire | default('86400') }}"
    state: present
    enabled: true

- name: Configure OpenBao DNF repository
  script:
    cmd: "{{ role_path }}/../../../../deployment/.scripts/configure-mirror-openbao-rpm.sh"

- name: Touch repo file
  file:
    path: "/etc/yum.repos.d/xroad.repo"
    modification_time: now

- name: Install required packages
  become: true
  package:
    name:
      - curl
      - cronie
      - tar
      - acl
      - tzdata-java
    state: present