---
hurl_version: "6.1.1"
hurl_install_dir: "/opt/hurl"
hurl_scenario_dir: "{{ playbook_dir }}/../hurl/scenarios"
hurl_files:
  - setup.hurl
  - setup_dsp.hurl
  - test-proxy-rest.hurl
  - test-proxy-soap.hurl
  - test-proxy-dsp.hurl
hurl_env_file: "files/vars.env"
