<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
    xmlns:xrd="http://x-road.ee/xsd/x-road.xsd"
    xmlns:tns="http://xroad-andmekogu.x-road.ee/producer"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    name="xroadService"
    targetNamespace="http://xroad-andmekogu.x-road.ee/producer">
  <wsdl:types>
    <xsd:schema targetNamespace="http://xroad-andmekogu.x-road.ee/producer">
    </xsd:schema>
  </wsdl:types>

  <!-- All the rest will be defined on the fly. -->

  <wsdl:portType name="xroadServicePortType">
    <!-- Operations go here -->
  </wsdl:portType>

  <wsdl:binding name="xroadServiceBinding" type="tns:xroadServicePortType">
    <soap:binding style="document"
      transport="http://schemas.xmlsoap.org/soap/http" />
    <!-- Operations go here -->
  </wsdl:binding>

  <wsdl:service name="xroad-andmekoguService">
    <!-- Port goes here -->
  </wsdl:service>

</wsdl:definitions>
