package org.niis.xroad.test.ui.glue.centralserver;

import com.codeborne.selenide.Condition;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.When;
import org.niis.xroad.test.ui.glue.BaseUiStepDefs;
import org.niis.xroad.test.ui.glue.constants.Constants;
import org.openqa.selenium.By;

import static com.codeborne.selenide.Selenide.$;
import static org.openqa.selenium.By.xpath;

public class CentralServerSettingsStepDefs extends BaseUiStepDefs {

    private static final By TAB_SETTINGS = xpath("//div[contains(@class, \"v-tabs-bar__content\")]//*[contains(@class,"
            + "\"v-tab\") and contains(text(), \"Settings\")]");
    private static final By TAB_SYSTEM_SETTINGS = xpath("//*[@data-test=\"systemsettings-tab-button\"]");
    private static final By BTN_ADD_MEMBER_CLASS = xpath("//*[@data-test=\"system-settings-add-member-class-button\"]");
    private static final By INPUT_MEMBER_CLASS_CODE =
            xpath("//*[@data-test=\"system-settings-member-class-code-edit-field\"]");
    private static final By INPUT_MEMBER_CLASS_DESCRIPTION =
            xpath("//*[@data-test=\"system-settings-member-class-description-edit-field\"]");

    @Given("CentralServer Settings tab is selected")
    public void userNavigatesToSettingsTab() {
        $(TAB_SETTINGS).click();
    }

    @Given("System settings tab is selected")
    public void userNavigatesToSystemSettingsTab() {
        $(TAB_SYSTEM_SETTINGS).click();
    }

    @When("A new memberclass {} is added")
    public void memberClassIsAdded(String code) {
        $(BTN_ADD_MEMBER_CLASS).click();
        $(INPUT_MEMBER_CLASS_CODE).setValue(code);
        $(INPUT_MEMBER_CLASS_DESCRIPTION).setValue("Generated by e2e-tests");
        $(Constants.BTN_DIALOG_SAVE).shouldBe(Condition.enabled).click();

        $(Constants.SNACKBAR_SUCCESS).shouldBe(Condition.visible);
        $(Constants.BTN_CLOSE_SNACKBAR).click();
    }

}
