-- data populated for the integration tests
-- SQL needs to be defined in terms of autogenerated HSQL table structure, not the actual PostgreSQL tables.
-- for example column name CLIENT.IS_AUTHENTICATION, not client.isauthentication

INSERT INTO UIUSER(ID, USERNAME, LOCALE) values (1, 'testuser', null);

INSERT INTO IDENTIFIER(ID, DISCRIMINATOR, TYPE, X_ROAD_INSTANCE, MEMBER_CLASS, MEMBER_CODE, SUBSYSTEM_CODE)
values (1, 'C', 'MEMBER', 'FI', 'GOV', 'M1', null);
INSERT INTO IDENTIFIER(ID, DISCRIMINATOR, TYPE, X_ROAD_INSTANCE, MEMBER_CLASS, MEMBER_CODE, SUBSYSTEM_CODE)
values (2, 'C', 'SUBSYSTEM', 'FI', 'GOV', 'M1', 'SS1');
INSERT INTO IDENTIFIER(ID, DISCRIMINATOR, TYPE, X_ROAD_INSTANCE, MEMBER_CLASS, MEMBER_CODE, SUBSYSTEM_CODE)
values (3, 'C', 'SUBSYSTEM', 'FI', 'GOV', 'M1', 'SS2');

INSERT INTO CLIENT(ID, CONF_ID, IDENTIFIER, CLIENT_STATUS, IS_AUTHENTICATION)
values (1,null,1,'registered', 'NOSSL');
INSERT INTO CLIENT(ID, CONF_ID, IDENTIFIER, CLIENT_STATUS, IS_AUTHENTICATION)
values (2,null,2,'registered', 'SSLNOAUTH');
INSERT INTO CLIENT(ID, CONF_ID, IDENTIFIER, CLIENT_STATUS, IS_AUTHENTICATION)
values (3,null,3,'registered', 'SSLNOAUTH');

INSERT INTO LOCALGROUP(ID, GROUP_CODE, DESCRIPTION, UPDATED, CLIENT_ID)
values (1, 'group1', 'foo', now(), 2);
INSERT INTO LOCALGROUP(ID, GROUP_CODE, DESCRIPTION, UPDATED, CLIENT_ID)
values (2, 'group2', 'foo', now(), 2);

INSERT INTO SERVERCONF(ID, server_code, OWNER) values (1, 'TEST-INMEM-SS', 1);

UPDATE CLIENT SET CONF_ID = 1;

INSERT INTO SERVICEDESCRIPTION (ID, CLIENT_ID, URL, DISABLED, DISABLED_NOTICE, REFRESHED_DATE, TYPE)
values (1, 2, 'https://soapservice.com/v1/Endpoint?wsdl', false, 'Out of order', now(), 'WSDL');

INSERT INTO SERVICEDESCRIPTION (ID, CLIENT_ID, URL, DISABLED, DISABLED_NOTICE, REFRESHED_DATE, TYPE)
values (2, 2, 'https://restservice.com/api/v1', true, 'Kaputt', now(), 'OPENAPI3');

INSERT INTO SERVICE (ID, SERVICEDESCRIPTION_ID, SERVICE_CODE, SERVICE_VERSION, TITLE, URL, SSL_AUTHENTICATION, TIMEOUT)
values (1, 1, 'getRandom', 'v1', 'getrandom-title', 'https://soapservice.com/v1/Endpoint', true, 60);

INSERT INTO SERVICE (ID, SERVICEDESCRIPTION_ID, SERVICE_CODE, SERVICE_VERSION, TITLE, URL, SSL_AUTHENTICATION, TIMEOUT)
values (2, 1, 'calculatePrime', 'v1', null, 'https://soapservice.com/v1/Endpoint', false, 60);

INSERT INTO SERVICE (ID, SERVICEDESCRIPTION_ID, SERVICE_CODE, SERVICE_VERSION, TITLE, URL, SSL_AUTHENTICATION, TIMEOUT)
values (3, 2, 'test-rest-servicecode', 'v1', null, 'https://restservice.com/api/v1', true, 60);

