# extract version number from "version" query parameter
map $args $version {
        default                         "2";
        "~(^|&)version=(?P<V>\d+)(&|$)" $V;
}
server {
        listen 80 default_server;
        server_name cs;

        root /var/lib/xroad/public;
        location ~ ^/(internal|external)conf$ {
           try_files /V$version$uri =404;
           expires -1;
        }
}

server {
        listen 1080;
        server_name mock-server;

        root /var/lib/xroad/services;
        location / {
           try_files $uri $uri/ =404;
        }
}

