name: Publish test CA image
on: 
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/publish_testca.yaml'
      - 'Docker/testca/**'
      - 'ansible/roles/xroad-ca/**'
env:
  REGISTRY: ghcr.io
  XROAD_HOME: ${{ github.workspace }}
jobs:
  PublishCS:
    name: Publish test CA image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Initialize docker setup
        working-directory: ./Docker/testca
        run: ./init_context.sh
      - name: Log in to the Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: ${{ github.workspace }}/Docker/testca
          push: true
          tags: ghcr.io/nordic-institute/xrddev-testca:latest
      - name: Clean old CA images
        uses: snok/container-retention-policy@b56f4ff7539c1f94f01e5dc726671cd619aa8072 # v2
        with:
          image-names: xrddev-testca
          cut-off: 1 week ago UTC
          timestamp-to-use: created_at
          account-type: org
          org-name: nordic-institute
          keep-at-least: 1
          token-type: github-token
          token: ${{ secrets.GITHUB_TOKEN }}
