name: Publish test CA image
on: 
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/publish_testca.yaml'
      - 'development/docker/testca/**'
      - 'development/ansible/roles/xroad-ca/**'
env:
  REGISTRY: ghcr.io
  XROAD_HOME: ${{ github.workspace }}
jobs:
  PublishCA:
    name: Publish test CA image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Initialize docker setup
        working-directory: ./development/docker/testca
        run: ./init_context.sh
      - name: Log in to the Container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: ${{ github.workspace }}/development/docker/testca
          push: true
          tags: ghcr.io/nordic-institute/xrddev-testca:latest
      - name: Clean old CA images
        uses: snok/container-retention-policy@d3bdcf5ce9b05f685154e4a16c39233b245e3d53 # v3.1.0
        with:
          image-names: xrddev-testca
          cut-off: 1w
          timestamp-to-use: created_at
          account: nordic-institute
          keep-n-most-recent: 1
          token: ${{ secrets.GITHUB_TOKEN }}
